<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FavoriteUserMoreOptions_Object</name>
   <tag></tag>
   <elementGuidId>c5e9fec0-f83a-4683-9532-8c185726af37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.rcx-sidebar-item:nth-child(3)>div.rcx-sidebar-item__wrapper>div.rcx-sidebar-item__content>div.rcx-sidebar-item__menu-wraper>button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
