<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Favorites_Object</name>
   <tag></tag>
   <elementGuidId>ce2886c8-ed72-409f-882b-1949837bf143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.rcx-sidebar-item:nth-child(3)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
