class LocalData:
    user_name = "rocketchat.internal.admin.test"
    password = "rocketchat.internal.admin.test"
    url = "http://localhost:3000/"
    channel_name = "channel1"
    user = "localuser"
    discussion_channel = "general"
    discussion_name = "Discussion1"
    discussion_message = "Test Local Discussion"
    message = "Hello testing"
    LOGIN_PAGE_TITLE = "Rocket.Chat"
    HOMEPAGE_HEADER = "Home"
    PUBLIC_CHANNEL = "general"
    QUOTE = "Testing quote"
    EMOJI_SEARCH = "Smiley"
    REPLY_IN_THREAD = "Testing reply in thread"
    JOIN_CHANNEL = "general"
    caption = "Test audio"

    # Create New user data
    new_user = "LocalUser"
    new_username = "localuser"
    new_email = "testlocal@gmail.com"
    new_status = "Test status message"
    new_bio = "Test Bio"
    new_nickname = "localuser"
    new_password = "Test@01"
    new_message = "Hello new user testing"

    # Team Data
    team_name = "Team1"
    team_topic = "Testing Teams Feature"
    new_channel = "ANewChannel"
    channel2team = "channeltoteam"
    new_name = "edited"
    channel = "channel2"