class LocalData:
    user_name = "rocketchat.internal.admin.test"
    password = "rocketchat.internal.admin.test"
    url = "http://localhost:3000/"
    channel_name = "channel1"
    user = "local1"
    discussion_channel = "general"
    discussion_name = "Discussion1"
    discussion_message = "Test Local Discussion"
    message = "Hello testing"
    LOGIN_PAGE_TITLE = "Rocket.Chat"
    HOMEPAGE_HEADER = "Home"
    PUBLIC_CHANNEL = "general"
    QUOTE = "Testing quote"
    EMOJI_SEARCH = "Smiley"
    REPLY_IN_THREAD = "Testing reply in thread"
    JOIN_CHANNEL = "general"

    # Create New user data
    new_user = "LocalUser1"
    new_username = "local1"
    new_email = "testlocal1@gmail.com"
    new_status = "Test status message"
    new_bio = "Test Bio"
    new_nickname = "local1"
    new_password = "Test@01"
    new_message = "Hello new user testing"