class LocalData:
    user_name = "ishrat.manzoor@rocket.chat"
    password = "Welcome@123"
    url = "http://localhost:3000/"
    channel_name = "channel2"
    user = "meher"
    discussion_channel = "general"
    discussion_name = "Discussion2"
    discussion_message = "Test Local Discussion"
    message = "Hello testing"
    LOGIN_PAGE_TITLE = "Rocket.Chat"
    HOMEPAGE_HEADER = "Home"
    PUBLIC_CHANNEL = "general"
    QUOTE = "Testing quote"
    EMOJI_SEARCH = "Smiley"
    REPLY_IN_THREAD = "Testing reply in thread"
    JOIN_CHANNEL = "general"

    # Create New user data
    new_user = "LocalUser2"
    new_username = "local2"
    new_email = "testlocal2@gmail.com"
    new_status = "Test status message"
    new_bio = "Test Bio"
    new_nickname = "local2"
    new_password = "Test@02"
    new_message = "Hello new user testing"