<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ReactionMessage_Object</name>
   <tag></tag>
   <elementGuidId>c16acee9-32b8-4a82-a24f-d0066f18083c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.wrapper>ul>li:last-child</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.wrapper>ul>li:last-child</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
