<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DyanmicChannel_Object</name>
   <tag></tag>
   <elementGuidId>a82c2574-5871-4fa9-8539-d478327c58d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.rcx-sidebar-item:nth-child(13)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
