<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JoinButton_Object</name>
   <tag></tag>
   <elementGuidId>0b7baaf9-a51e-4331-a997-be260b13b4ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.js-join</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
