<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ScrollTochannel_Object</name>
   <tag></tag>
   <elementGuidId>d2456e62-3c69-4d83-99fd-da9c9ecd75f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.rcx-sidebar-item:nth-child(10)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
