# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Run QA Regression

on:
  push:
    branches:
      - develop
      - main


jobs:
  test:
    name: Running end to end tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U selenium
        pip install pytest pytest-html
        pip install allure-pytest

    - name: Test
      env:
        TEST_MODE: "true"
        MONGO_URL: mongodb://localhost:27017/rocketchat
        MONGO_OPLOG_URL: mongodb://localhost:27017/local
      run: |
        RUN_TESTS=no node .scripts/start.js &

        # wait until port is bind
        timeout 60 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do sleep 1; done' localhost 3000

        cd ..
        cd QA.Automation
        pytest -v -s --alluredir="./reports/allure_reports" Tests
