name: Run QA

on:
  push:
    branches:
      - develop
      - main

jobs:
  test:
    name: Running end to end tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2

    - name: use docker image
      uses: docker://rocketchat/rocket.chat.preview:3.10.4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U selenium
        pip install pytest pytest-html
        pip install allure-pytest

    - name: 'BrowserStack Env Setup'
      uses: 'browserstack/github-actions/setup-env@master'
      with:
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}


    - name: 'Start BrowserStackLocal Tunnel'
      uses: 'browserstack/github-actions/setup-local@master'
      with:
        local-testing: 'start'
        local-logging-level: 'all-logs'
        local-identifier: 'random'

    - name: Test
      run: |
        cd ..
        cd QA.Automation
        pytest -v -s --alluredir="./reports/allure_reports" Tests

    - name: 'Stop BrowserStackLocal'
      uses: 'browserstack/github-actions/setup-local@master'
      with:
        local-testing: stop