name: CI

on:
  pull_request:
    branches: '**'
  push:
    branches:
      - ci

jobs:
  test:
    name: Running end to end tests
    runs-on: ubuntu-latest

    # container: node:10.18-jessie
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      rocketchat:
        # Docker Hub image
        image: rocketchat/rocket.chat.preview:3.10.4
        ports:
          # Opens tcp port 6379 on the host and service container
          - 80:80

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2

    # - name: use docker image
      # Containers must run in Linux based operating systems
      # runs-on: ubuntu-latest
      # Docker Hub image that `container-job` executes in

      # with:
        # python-version: 3.9

    - name: Install dependencies
      run: |
        curl http://localhost
        python -m pip install --upgrade pip
        pip install -U selenium
        pip install pytest pytest-html
        pip install allure-pytest

    - name: 'BrowserStack Env Setup'
      uses: 'browserstack/github-actions/setup-env@master'
      with:
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}


    - name: 'Start BrowserStackLocal Tunnel'
      uses: 'browserstack/github-actions/setup-local@master'
      with:
        local-testing: 'start'
        local-logging-level: 'all-logs'
        local-identifier: 'random'

    - name: Test
      run: |
        cd ..
        cd QA.Automation
        pytest -v -s --alluredir="./reports/allure_reports" Tests

    - name: 'Stop BrowserStackLocal'
      uses: 'browserstack/github-actions/setup-local@master'
      with:
        local-testing: stop